
services:
  frontend:
    container_name: lms-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    ports:
      - "80:80"
#    volumes:
#      - ./frontend/dist:/usr/share/nginx/html:ro
#      - ./frontend/nginx/lms-frontend.local.conf:/etc/nginx/lms-frontend.local.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - lms-network      

  backend:
    container_name: lms-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 7007:7007
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - lms-network

  mariadb:
    container_name: lms-mariadb
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/glocalview_lms.sql:/docker-entrypoint-initdb.d/glocalview_lms.sql  

    healthcheck:
      test:
          [
            "CMD",
            "mysqladmin",
            "ping",
            "-h",
            "localhost",
            "-u",
            "root",
            "-p${DB_PASSWORD}"
          ]   
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms-network

volumes:
  mariadb_data:

networks:
  lms-network:
    driver: bridge

services:
  frontend:
    container_name: lms-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx/lms-frontend.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - lms-network

  backend:
    container_name: lms-backend
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "7007:7007"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - lms-network

  mariadb:
    container_name: lms-mariadb
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lms
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lmspass
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mariadb_data:

