const cityData = [
  // #Andaman and Nicobar Islands
  { name: "Bambooflat", state_id: 1 },
  { name: "Port Blair", state_id: 1 },
  { name: "Diglipur", state_id: 1 },
  { name: "Mayabunder", state_id: 1 },
  { name: "Rangat", state_id: 1 },
  { name: "Neil Island", state_id: 1 },
  { name: "Long Island", state_id: 1 },
  { name: "Wandoor", state_id: 1 },
  { name: "Car Nicobar", state_id: 1 },
  // #Andhra Pradesh
  { name: "Vijayawada", state_id: 2 },
  { name: "Guntur", state_id: 2 },
  { name: "Kurnool", state_id: 2 },
  { name: "Rajahmundry", state_id: 2 },
  { name: "Nellore", state_id: 2 },
  { name: "Kakinada", state_id: 2 },
  { name: "Vizianagaram", state_id: 2 },
  { name: "Chittoor", state_id: 2 },
  { name: "Tirupati", state_id: 2 },
  { name: "Anantapur", state_id: 2 },
  { name: "Kadapa", state_id: 2 },
  { name: "Machilipatnam", state_id: 2 },
  { name: "Amaravati", state_id: 2 },
  { name: "Eluru", state_id: 2 },
  { name: "Sri Potti Sriramulu Nellore", state_id: 2 },
  { name: "Amalapuram", state_id: 2 },
  { name: "Mangalagiri", state_id: 2 },
  { name: "Srikalahasti", state_id: 2 },
  { name: "Srikakulam", state_id: 2 },
  { name: "Gudivada", state_id: 2 },
  // #Arunachal Pradesh
  { name: "Aalo", state_id: 3 },
  { name: "Anini", state_id: 3 },
  { name: "Basar", state_id: 3 },
  { name: "Boleng", state_id: 3 },
  { name: "Bomdila", state_id: 3 },
  { name: "Changlang", state_id: 3 },
  { name: "Daporijo", state_id: 3 },
  { name: "Deomali", state_id: 3 },
  { name: "Dirang", state_id: 3 },
  { name: "Hawai", state_id: 3 },
  { name: "Itanagar", state_id: 3 },
  { name: "Jairampur", state_id: 3 },
  { name: "Khonsa", state_id: 3 },
  { name: "Koloriang", state_id: 3 },
  { name: "Miao", state_id: 3 },
  { name: "Naharlagun", state_id: 3 },
  { name: "Namsai", state_id: 3 },
  { name: "Pasighat", state_id: 3 },
  { name: "Roing", state_id: 3 },
  { name: "Rupa", state_id: 3 },
  { name: "Sagalee", state_id: 3 },
  { name: "Seppa", state_id: 3 },
  { name: "Tawang", state_id: 3 },
  { name: "Tezu", state_id: 3 },
  { name: "Yingkiong", state_id: 3 },
  { name: "Ziro", state_id: 3 },
  // #Assam
  { name: "Guwahati", state_id: 4 },
  { name: "Jorhat", state_id: 4 },
  { name: "Tezpur", state_id: 4 },
  { name: "Dibrugarh", state_id: 4 },
  { name: "Bongaigaon", state_id: 4 },
  { name: "Silchar", state_id: 4 },
  { name: "Golaghat", state_id: 4 },
  { name: "Barpeta", state_id: 4 },
  { name: "Hailakandi", state_id: 4 },
  { name: "Kokrajhar", state_id: 4 },
  { name: "Haflong", state_id: 4 },
  { name: "Cachar", state_id: 4 },
  { name: "Sonitpur", state_id: 4 },
  { name: "Karbi Anglong", state_id: 4 },
  { name: "Diphu", state_id: 4 },
  { name: "Dispur", state_id: 4 },
  { name: "Digboi", state_id: 4 },
  { name: "Shillong", state_id: 4 },
  { name: "Bilasipara", state_id: 4 },
  { name: "Chabua", state_id: 4 },
  { name: "Gohpur", state_id: 4 },
  { name: "Kharupetia", state_id: 4 },
  { name: "Bokajan", state_id: 4 },
  { name: "Rangapara", state_id: 4 },
  // #Bihar
  { name: "Patna", state_id: 5 },
  { name: "Gaya", state_id: 5 },
  { name: "Bhagalpur", state_id: 5 },
  { name: "Darbhanga", state_id: 5 },
  { name: "Begusarai", state_id: 5 },
  { name: "Buxar", state_id: 5 },
  { name: "Munger", state_id: 5 },
  { name: "Saharsa", state_id: 5 },
  { name: "Nawada", state_id: 5 },
  { name: "Sasaram", state_id: 5 },
  { name: "Bihar Sharif", state_id: 5 },
  { name: "Chhapra", state_id: 5 },
  { name: "Arrah", state_id: 5 },
  { name: "Bettiah", state_id: 5 },
  { name: "Hajipur", state_id: 5 },
  { name: "Danapur", state_id: 5 },
  { name: "Muzaffarpur", state_id: 5 },
  { name: "Katihar", state_id: 5 },
  { name: "Motihari", state_id: 5 },
  // #Chandigarh
  { name: "Chandigarh", state_id: 6 },
  // #Chhattisgarh
  { name: "Raipur", state_id: 7 },
  { name: "Mahasamund", state_id: 7 },
  { name: "Bilaspur", state_id: 7 },
  { name: "Raigarh", state_id: 7 },
  { name: "Korba", state_id: 7 },
  { name: "Rajnandgaon", state_id: 7 },
  { name: "Dhamtari", state_id: 7 },
  { name: "Kanker", state_id: 7 },
  { name: "Bhilai", state_id: 7 },
  { name: "Sakti", state_id: 7 },
  { name: "Sarangarh", state_id: 7 },
  { name: "Khairagarh", state_id: 7 },
  { name: "Ratanpur", state_id: 7 },
  { name: "Mungeli", state_id: 7 },
  { name: "Durg", state_id: 7 },
  { name: "Balrampur", state_id: 7 },
  { name: "Atal Nagar-Nava Raipur", state_id: 7 },
  // #Dadra and Nagar Haveli
  { name: "Silvassa", state_id: 8 },
  { name: "Naroli", state_id: 8 },
  { name: "Khanvel", state_id: 8 },
  { name: "Rakholi", state_id: 8 },
  { name: "Dadra", state_id: 8 },
  { name: "Dudhani", state_id: 8 },
  { name: "Saily", state_id: 8 },
  { name: "Vapi ", state_id: 8 },
  // #Daman and Diu
  { name: "Daman", state_id: 9 },
  { name: "Ghoghla", state_id: 9 },
  { name: "Diu", state_id: 9 },
  // #Delhi
  { name: "New Delhi", state_id: 10 },
  { name: "North Delhi", state_id: 10 },
  { name: "South Delhi", state_id: 10 },
  { name: "East Delhi", state_id: 10 },
  { name: "West Delhi", state_id: 10 },
  { name: "Central Delhi", state_id: 10 },
  { name: "North East Delhi", state_id: 10 },
  { name: "North West Delhi", state_id: 10 },
  { name: "South West Delhi", state_id: 10 },
  { name: "South East Delhi", state_id: 10 },
  { name: "Shahdara", state_id: 10 },
  { name: "Dwarka", state_id: 10 },
  { name: "Narela", state_id: 10 },
  { name: "Rohini", state_id: 10 },
  { name: "Connaught Place", state_id: 10 },
  { name: "Karol Bagh", state_id: 10 },
  { name: "Chandni Chowk", state_id: 10 },
  { name: "Paharganj", state_id: 10 },
  { name: "Hauz Khas", state_id: 10 },
  { name: "Saket", state_id: 10 },
  { name: "Vasant Kunj", state_id: 10 },
  { name: "Lajpat Nagar", state_id: 10 },
  { name: "Janakpuri", state_id: 10 },
  { name: "Patel Nagar", state_id: 10 },
  { name: "Rajouri Garden", state_id: 10 },
  { name: "Dilshad Garden", state_id: 10 },
  // #Goa
  { name: "Panaji", state_id: 11 },
  { name: "Margao", state_id: 11 },
  { name: "Ponda", state_id: 11 },
  { name: "Canacona", state_id: 11 },
  { name: "Vasco da Gama", state_id: 11 },
  { name: "Valpoi", state_id: 11 },
  // #Gujarat
  { name: "Ahmedabad", state_id: 12 },
  { name: "Vadodara", state_id: 12 },
  { name: "Surat", state_id: 12 },
  { name: "Gandhinagar", state_id: 12 },
  { name: "Rajkot", state_id: 12 },
  { name: "Jamnagar", state_id: 12 },
  { name: "Bhavnagar", state_id: 12 },
  { name: "Junagadh", state_id: 12 },
  { name: "Porbandar", state_id: 12 },
  { name: "Bharuch", state_id: 12 },
  { name: "Patan", state_id: 12 },
  { name: "Valsad", state_id: 12 },
  { name: "Surendranagar", state_id: 12 },
  { name: "Dahod", state_id: 12 },
  { name: "Morbi", state_id: 12 },
  { name: "Gondal", state_id: 12 },
  { name: "Kalol", state_id: 12 },
  { name: "Dwarka", state_id: 12 },
  { name: "Navsari", state_id: 12 },
  { name: "Amreli", state_id: 12 },
  { name: "Bhuj", state_id: 12 },
  { name: "Gandhidham", state_id: 12 },
  { name: "Himatnagar", state_id: 12 },
  // #Haryana
  { name: "Gurgaon", state_id: 13 },
  { name: "Faridabad", state_id: 13 },
  { name: "Karnal", state_id: 13 },
  { name: "Ambala", state_id: 13 },
  { name: "Panipat", state_id: 13 },
  { name: "Panchkula", state_id: 13 },
  { name: "Hisar", state_id: 13 },
  { name: "Kurukshetra", state_id: 13 },
  { name: "Rewari", state_id: 13 },
  { name: "Sonipat", state_id: 13 },
  { name: "Jind", state_id: 13 },
  { name: "Kaithal", state_id: 13 },
  { name: "Sirsa", state_id: 13 },
  { name: "Palwal", state_id: 13 },
  { name: "Yamunanagar", state_id: 13 },
  { name: "Narnaul", state_id: 13 },
  { name: "Ambala Sadar", state_id: 13 },
  { name: "Rohtak", state_id: 13 },
  { name: "Bhiwani", state_id: 13 },
  { name: "Mahendragarh", state_id: 13 },
  { name: "Bahadurgarh", state_id: 13 },
  // #Himachal Pradesh
  { name: "Shimla", state_id: 14 },
  { name: "Dharamsala", state_id: 14 },
  { name: "Kullu", state_id: 14 },
  { name: "Kangra", state_id: 14 },
  { name: "Chamba", state_id: 14 },
  { name: "Solan", state_id: 14 },
  { name: "Hamirpur", state_id: 14 },
  { name: "Manali", state_id: 14 },
  { name: "Palampur", state_id: 14 },
  { name: "Kasauli", state_id: 14 },
  { name: "Nahan", state_id: 14 },
  { name: "Dalhousie", state_id: 14 },
  { name: "Baddi", state_id: 14 },
  { name: "Narkanda", state_id: 14 },
  { name: "Chail", state_id: 14 },
  { name: "Paonta Sahib", state_id: 14 },
  { name: "Kufri", state_id: 14 },
  { name: "Baijnath", state_id: 14 },
  // #Jammu and Kashmir
  { name: "Srinagar", state_id: 15 },
  { name: "Jammu", state_id: 15 },
  { name: "Anantnag", state_id: 15 },
  { name: "Pahalgam", state_id: 15 },
  { name: "Kathua", state_id: 15 },
  { name: "Rajouri", state_id: 15 },
  { name: "Doda", state_id: 15 },
  { name: "Leh", state_id: 15 },
  { name: "Ganderbal", state_id: 15 },
  { name: "Kishtwar", state_id: 15 },
  { name: "Gulmarg", state_id: 15 },
  { name: "Katra", state_id: 15 },
  // #Jharkhand
  { name: "Ranchi", state_id: 16 },
  { name: "Dhanbad", state_id: 16 },
  { name: "Jamshedpur", state_id: 16 },
  { name: "Hazaribagh", state_id: 16 },
  { name: "Bokaro Steel City", state_id: 16 },
  { name: "Deoghar", state_id: 16 },
  { name: "Giridih", state_id: 16 },
  { name: "Medininagar", state_id: 16 },
  { name: "Ramgarh", state_id: 16 },
  { name: "Phusro", state_id: 16 },
  { name: "Chirkunda", state_id: 16 },
  { name: "Jhumri Telaiya", state_id: 16 },
  // #Karnataka
  { name: "Bangalore", state_id: 17 },
  { name: "Mangalore", state_id: 17 },
  { name: "Bidar", state_id: 17 },
  { name: "Bijapur", state_id: 17 },
  { name: "Belgaum", state_id: 17 },
  { name: "Mandya", state_id: 17 },
  { name: "Hassan", state_id: 17 },
  { name: "Davanagere", state_id: 17 },
  { name: "Bellary", state_id: 17 },
  { name: "Shimoga", state_id: 17 },
  { name: "Gulbarga", state_id: 17 },
  { name: "Chikmagalur", state_id: 17 },
  { name: "Hospet", state_id: 17 },
  { name: "Raichur", state_id: 17 },
  { name: "Bagalkot", state_id: 17 },
  { name: "Bhadravati", state_id: 17 },
  // #Kerala
  { name: "Kochi", state_id: 18 },
  { name: "Thiruvananthapuram", state_id: 18 },
  { name: "Kozhikode", state_id: 18 },
  { name: "Kottayam", state_id: 18 },
  { name: "Thrissur", state_id: 18 },
  { name: "Kollam", state_id: 18 },
  { name: "Wayanad", state_id: 18 },
  { name: "Kannur", state_id: 18 },
  { name: "Alappuzha", state_id: 18 },
  { name: "Malappuram", state_id: 18 },
  { name: "Palakkad", state_id: 18 },
  { name: "Kasaragod", state_id: 18 },
  { name: "Ernakulam", state_id: 18 },
  { name: "Idukki", state_id: 18 },
  { name: "Pathanamthitta", state_id: 18 },
  { name: "Aluva", state_id: 18 },
  { name: "Punalur", state_id: 18 },
  { name: "Varkala", state_id: 18 },
  { name: "Nilambur", state_id: 18 },
  { name: "Mannarkkad", state_id: 18 },
  { name: "Ottapalam", state_id: 18 },
  // #Ladakh
  { name: "Kargil", state_id: 19 },
  { name: "Leh", state_id: 19 },
  // #Lakshadweep
  { name: "Kavaratti", state_id: 20 },
  { name: "Lakshadweep", state_id: 20 },
  { name: "Amini", state_id: 20 },
  { name: "Andrott", state_id: 20 },
  { name: "Kadmat", state_id: 20 },
  { name: "Kalpeni", state_id: 20 },
  { name: "Minicoy", state_id: 20 },
  // #Madhya Pradesh
  { name: "Bhopal", state_id: 21 },
  { name: "Indore", state_id: 21 },
  { name: "Gwalior", state_id: 21 },
  { name: "Jabalpur", state_id: 21 },
  { name: "Ujjain", state_id: 21 },
  { name: "Dewas", state_id: 21 },
  { name: "Burhanpur", state_id: 21 },
  { name: "Narmadapuram", state_id: 21 },
  { name: "Chhindwara", state_id: 21 },
  { name: "Chhatarpur", state_id: 21 },
  { name: "Betul", state_id: 21 },
  { name: "Khargone", state_id: 21 },
  { name: "Vidisha", state_id: 21 },
  { name: "Orchha", state_id: 21 },
  { name: "Mandav", state_id: 21 },
  { name: "Bhind", state_id: 21 },
  { name: "Rewa", state_id: 21 },
  { name: "Sagar", state_id: 21 },
  { name: "Satna", state_id: 21 },
  { name: "Ratlam", state_id: 21 },
  { name: "Khandwa", state_id: 21 },
  { name: "Katni", state_id: 21 },
  { name: "Guna", state_id: 21 },
  { name: "Shivpuri", state_id: 21 },
  { name: "Morena", state_id: 21 },
  { name: "Itarsi", state_id: 21 },
  { name: "Hoshangabad", state_id: 21 },
  { name: "Mandsaur", state_id: 21 },
  { name: "Neemuch", state_id: 21 },
  { name: "Chhatarpur", state_id: 21 },
  { name: "Damoh", state_id: 21 },
  { name: "Sehore", state_id: 21 },
  { name: "Pithampur", state_id: 21 },
  { name: "Singrauli", state_id: 21 },
  { name: "Shahdol", state_id: 21 },
  { name: "Harda", state_id: 21 },
  { name: "Betul", state_id: 21 },
  { name: "Balaghat", state_id: 21 },
  { name: "Rajgarh", state_id: 21 },
  { name: "Mandla", state_id: 21 },
  { name: "Narsinghpur", state_id: 21 },
  { name: "Anuppur", state_id: 21 },
  { name: "Seoni", state_id: 21 },
  // #Maharashtra
  { name: "Pune", state_id: 22 },
  { name: "Mumbai", state_id: 22 },
  { name: "Nagpur", state_id: 22 },
  { name: "Aurangabad", state_id: 22 },
  { name: "Nashik", state_id: 22 },
  { name: "Kolhapur", state_id: 22 },
  { name: "Amravati", state_id: 22 },
  { name: "Solapur", state_id: 22 },
  { name: "Thane", state_id: 22 },
  { name: "Akola", state_id: 22 },
  { name: "Chandrapur", state_id: 22 },
  { name: "Nanded", state_id: 22 },
  { name: "Ahmednagar", state_id: 22 },
  { name: "Jalna", state_id: 22 },
  { name: "Satara", state_id: 22 },
  { name: "Navi Mumbai", state_id: 22 },
  { name: "Gondia", state_id: 22 },
  { name: "Yavatmal", state_id: 22 },
  { name: "Vasai-Virar", state_id: 22 },
  { name: "Raigad", state_id: 22 },
  { name: "Ulhasnagar", state_id: 22 },
  { name: "Ambarnath", state_id: 22 },
  { name: "Bhandara", state_id: 22 },
  { name: "Malegaon", state_id: 22 },
  // #Manipur
  { name: "Imphal", state_id: 23 },
  { name: "Thoubal", state_id: 23 },
  { name: "Kakching", state_id: 23 },
  { name: "Bishnupur", state_id: 23 },
  { name: "Churachandpur", state_id: 23 },
  { name: "Senapati", state_id: 23 },
  { name: "Ukhrul", state_id: 23 },
  { name: "Tamenglong", state_id: 23 },
  { name: "Moreh", state_id: 23 },
  { name: "Mao", state_id: 23 },
  { name: "Jiribam", state_id: 23 },
  { name: "Chandel", state_id: 23 },
  { name: "Tengnoupal", state_id: 23 },
  // #Meghalaya
  { name: "Shillong", state_id: 24 },
  { name: "Tura", state_id: 24 },
  { name: "Jowai", state_id: 24 },
  { name: "Nongpoh", state_id: 24 },
  { name: "Baghmara", state_id: 24 },
  { name: "Williamnagar", state_id: 24 },
  { name: "Resubelpara", state_id: 24 },
  { name: "Khliehriat", state_id: 24 },
  { name: "Mawkyrwat", state_id: 24 },
  { name: "Nongstoin", state_id: 24 },
  { name: "Sohra", state_id: 24 },
  { name: "Mairang", state_id: 24 },
  { name: "Ampati", state_id: 24 },
  { name: "Amlarem", state_id: 24 },
  { name: "Dawki", state_id: 24 },
  // #Mizoram
  { name: "Aizawl", state_id: 25 },
  { name: "Lunglei", state_id: 25 },
  { name: "Saiha", state_id: 25 },
  { name: "Champhai", state_id: 25 },
  { name: "Kolasib", state_id: 25 },
  { name: "Serchhip", state_id: 25 },
  { name: "Lawngtlai", state_id: 25 },
  { name: "Mamit", state_id: 25 },
  { name: "Hnahthial", state_id: 25 },
  { name: "Saitual", state_id: 25 },
  // #Nagaland
  { name: "Kohima", state_id: 26 },
  { name: "Dimapur", state_id: 26 },
  { name: "Mokokchung", state_id: 26 },
  { name: "Tuensang", state_id: 26 },
  { name: "Wokha", state_id: 26 },
  { name: "Zunheboto", state_id: 26 },
  { name: "Mon", state_id: 26 },
  { name: "Phek", state_id: 26 },
  { name: "Longleng", state_id: 26 },
  { name: "Peren", state_id: 26 },
  { name: "Kiphire", state_id: 26 },
  // #Odisha
  { name: "Bhubaneswar", state_id: 27 },
  { name: "Cuttack", state_id: 27 },
  { name: "Rourkela", state_id: 27 },
  { name: "Berhampur", state_id: 27 },
  { name: "Sambalpur", state_id: 27 },
  { name: "Puri", state_id: 27 },
  { name: "Balasore", state_id: 27 },
  { name: "Bhadrak", state_id: 27 },
  { name: "Baripada", state_id: 27 },
  { name: "Jharsuguda", state_id: 27 },
  { name: "Bargarh", state_id: 27 },
  { name: "Kendujhar", state_id: 27 },
  { name: "Koraput", state_id: 27 },
  { name: "Rayagada", state_id: 27 },
  { name: "Dhenkanal", state_id: 27 },
  { name: "Jagatsinghpur", state_id: 27 },
  { name: "Paradeep", state_id: 27 },
  { name: "Anugul", state_id: 27 },
  { name: "Jajpur", state_id: 27 },
  { name: "Khurda", state_id: 27 },
  { name: "Nayagarh", state_id: 27 },
  { name: "Sundargarh", state_id: 27 },
  { name: "Kendrapara", state_id: 27 },
  { name: "Phulabani", state_id: 27 },
  { name: "Talcher", state_id: 27 },
  { name: "Paradip", state_id: 27 },
  { name: "Balangir", state_id: 27 },
  { name: "Rajgangpur", state_id: 27 },
  { name: "Sonepur", state_id: 27 },
  { name: "Bolangir", state_id: 27 },
  // #Puducherry
  { name: "Puducherry ", state_id: 28 },
  { name: "Karaikal", state_id: 28 },
  { name: "Mahe", state_id: 28 },
  { name: "Yanam", state_id: 28 },
  // #Punjab
  { name: "Chandigarh", state_id: 29 },
  { name: "Ludhiana", state_id: 29 },
  { name: "Amritsar", state_id: 29 },
  { name: "Jalandhar", state_id: 29 },
  { name: "Patiala", state_id: 29 },
  { name: "Bathinda", state_id: 29 },
  { name: "Hoshiarpur", state_id: 29 },
  { name: "Mohali", state_id: 29 },
  { name: "Batala", state_id: 29 },
  { name: "Pathankot", state_id: 29 },
  { name: "Moga", state_id: 29 },
  { name: "Firozpur", state_id: 29 },
  { name: "Kapurthala", state_id: 29 },
  { name: "Gurdaspur", state_id: 29 },
  { name: "Sangrur", state_id: 29 },
  { name: "Faridkot", state_id: 29 },
  { name: "Mansa", state_id: 29 },
  { name: "Barnala", state_id: 29 },
  { name: "Rajpura", state_id: 29 },
  { name: "Nabha", state_id: 29 },
  { name: "Abohar", state_id: 29 },
  { name: "Malerkotla", state_id: 29 },
  { name: "Khanna", state_id: 29 },
  { name: "Sunam", state_id: 29 },
  { name: "Dhuri", state_id: 29 },
  // #Rajasthan
  { name: "Beawar", state_id: 30 },
  { name: "Pali", state_id: 30 },
  { name: "Jaipur", state_id: 30 },
  { name: "Alwar", state_id: 30 },
  { name: "Baran", state_id: 30 },
  { name: "Dholpur", state_id: 30 },
  { name: "Udaipur", state_id: 30 },
  { name: "Bikaner", state_id: 30 },
  { name: "Tonk", state_id: 30 },
  { name: "Jodhpur", state_id: 30 },
  { name: "Ajmer", state_id: 30 },
  { name: "Bharatpur", state_id: 30 },
  { name: "Sikar", state_id: 30 },
  { name: "Bhilwara", state_id: 30 },
  { name: "Hanumangarh", state_id: 30 },
  { name: "Sri Ganganagar", state_id: 30 },
  { name: "Kishangarh", state_id: 30 },
  { name: "Banswara", state_id: 30 },
  { name: "Bhiwadi", state_id: 30 },
  { name: "Kota", state_id: 30 },
  { name: "Dungarpur", state_id: 30 },
  { name: "Gangapur", state_id: 30 },
  { name: "Sawai Madhopur", state_id: 30 },
  { name: "Nagaur", state_id: 30 },
  { name: "Jhunjhunu", state_id: 30 },
  { name: "Churu", state_id: 30 },
  { name: "Phalodi", state_id: 30 },
  { name: "Chittorgarh", state_id: 30 },
  { name: "Hindaun", state_id: 30 },
  { name: "Bundi", state_id: 30 },
  { name: "Behror", state_id: 30 },
  { name: "Sujangarh", state_id: 30 },
  { name: "Sanchore", state_id: 30 },
  { name: "Neem Ka Thana", state_id: 30 },
  { name: "Deeg", state_id: 30 },
  { name: "Kekri", state_id: 30 },
  { name: "Salumbar", state_id: 30 },
  { name: "Jaisalmer", state_id: 30 },
  { name: "Khairthal", state_id: 30 },
  { name: "Balotra", state_id: 30 },
  { name: "Dausa", state_id: 30 },
  { name: "Rajsamand", state_id: 30 },
  { name: "Merta", state_id: 30 },
  { name: "Shrimadhopur", state_id: 30 },
  { name: "Sumerpur", state_id: 30 },
  { name: "Nohar", state_id: 30 },
  // #Sikkim
  { name: "Gangtok", state_id: 31 },
  { name: "Namchi", state_id: 31 },
  { name: "Mangan", state_id: 31 },
  { name: "Gyalshing", state_id: 31 },
  { name: "Singtam", state_id: 31 },
  { name: "Rangpo", state_id: 31 },
  { name: "Jorethang", state_id: 31 },
  { name: "Pakyong", state_id: 31 },
  { name: "Rabongla", state_id: 31 },
  { name: "Soreng", state_id: 31 },
  // #Tamil Nadu
  { name: "Chennai", state_id: 32 },
  { name: "Coimbatore", state_id: 32 },
  { name: "Madurai", state_id: 32 },
  { name: "Tiruchirappalli", state_id: 32 },
  { name: "Salem", state_id: 32 },
  { name: "Tirunelveli", state_id: 32 },
  { name: "Erode", state_id: 32 },
  { name: "Vellore", state_id: 32 },
  { name: "Thoothukudi", state_id: 32 },
  { name: "Thanjavur", state_id: 32 },
  { name: "Nagercoil", state_id: 32 },
  { name: "Dindigul", state_id: 32 },
  { name: "Cuddalore", state_id: 32 },
  { name: "Kanchipuram", state_id: 32 },
  { name: "Tiruvannamalai", state_id: 32 },
  { name: "Karur", state_id: 32 },
  { name: "Ooty", state_id: 32 },
  { name: "Krishnagiri", state_id: 32 },
  { name: "Pudukkottai", state_id: 32 },
  { name: "Kumbakonam", state_id: 32 },
  { name: "Karaikudi", state_id: 32 },
  { name: "Hosur", state_id: 32 },
  { name: "Dharmapuri", state_id: 32 },
  { name: "Thiruvallur", state_id: 32 },
  { name: "Viluppuram", state_id: 32 },
  { name: "Namakkal", state_id: 32 },
  { name: "Ramanathapuram", state_id: 32 },
  { name: "Mayiladuthurai", state_id: 32 },
  // #Telangana
  { name: "Hyderabad", state_id: 33 },
  { name: "Secunderabad", state_id: 33 },
  { name: "Warangal", state_id: 33 },
  { name: "Nizamabad", state_id: 33 },
  { name: "Karimnagar", state_id: 33 },
  { name: "Ramagundam", state_id: 33 },
  { name: "Khammam", state_id: 33 },
  { name: "Mahabubnagar", state_id: 33 },
  { name: "Nalgonda", state_id: 33 },
  { name: "Adilabad", state_id: 33 },
  { name: "Siddipet", state_id: 33 },
  { name: "Suryapet", state_id: 33 },
  { name: "Jagtial", state_id: 33 },
  { name: "Nirmal", state_id: 33 },
  { name: "Mancherial", state_id: 33 },
  { name: "Kamareddy", state_id: 33 },
  { name: "Medak", state_id: 33 },
  { name: "Vikarabad", state_id: 33 },
  { name: "Wanaparthy", state_id: 33 },
  { name: "Sangareddy", state_id: 33 },
  { name: "Palwancha", state_id: 33 },
  // #Tripura
  { name: "Agartala", state_id: 34 },
  { name: "Udaipur", state_id: 34 },
  { name: "Dharmanagar", state_id: 34 },
  { name: "Belonia", state_id: 34 },
  { name: "Ambassa", state_id: 34 },
  { name: "Kailasahar", state_id: 34 },
  { name: "Sonamura", state_id: 34 },
  { name: "Santirbazar", state_id: 34 },
  { name: "Kumarghat", state_id: 34 },
  { name: "Sabroom", state_id: 34 },
  // #Uttar Pradesh
  { name: "Lucknow", state_id: 35 },
  { name: "Kanpur", state_id: 35 },
  { name: "Varanasi", state_id: 35 },
  { name: "Agra", state_id: 35 },
  { name: "Allahabad", state_id: 35 },
  { name: "Ghaziabad", state_id: 35 },
  { name: "Noida", state_id: 35 },
  { name: "Meerut", state_id: 35 },
  { name: "Aligarh", state_id: 35 },
  { name: "Bareilly", state_id: 35 },
  { name: "Moradabad", state_id: 35 },
  { name: "Saharanpur", state_id: 35 },
  { name: "Gorakhpur", state_id: 35 },
  { name: "Jhansi", state_id: 35 },
  { name: "Muzaffarnagar", state_id: 35 },
  { name: "Mathura", state_id: 35 },
  { name: "Rampur", state_id: 35 },
  { name: "Faizabad", state_id: 35 },
  { name: "Azamgarh", state_id: 35 },
  { name: "Firozabad", state_id: 35 },
  { name: "Basti", state_id: 35 },
  { name: "Shahjahanpur", state_id: 35 },
  { name: "Mirzapur", state_id: 35 },
  { name: "Jaunpur", state_id: 35 },
  { name: "Ballia", state_id: 35 },
  { name: "Hapur", state_id: 35 },
  { name: "Etawah", state_id: 35 },
  { name: "Bijnor", state_id: 35 },
  { name: "Loni", state_id: 35 },
  { name: "Rae Bareli", state_id: 35 },
  { name: "Orai", state_id: 35 },
  { name: "Bahraich", state_id: 35 },
  { name: "Sambhal", state_id: 35 },
  { name: "Sultanpur", state_id: 35 },
  { name: "Amroha", state_id: 35 },
  { name: "Hardoi", state_id: 35 },
  { name: "Raebareli", state_id: 35 },
  { name: "Unnao", state_id: 35 },
  { name: "Sitapur", state_id: 35 },
  { name: "Hathras", state_id: 35 },
  // #Uttarakhand
  { name: "Dehradun", state_id: 36 },
  { name: "Haridwar", state_id: 36 },
  { name: "Rishikesh", state_id: 36 },
  { name: "Haldwani", state_id: 36 },
  { name: "Nainital", state_id: 36 },
  { name: "Almora", state_id: 36 },
  { name: "Kashipur", state_id: 36 },
  { name: "Mussoorie", state_id: 36 },
  { name: "New Tehri", state_id: 36 },
  { name: "Chamoli", state_id: 36 },
  { name: "Pithoragarh", state_id: 36 },
  { name: "Bageshwar", state_id: 36 },
  { name: "Ranikhet", state_id: 36 },
  { name: "Kotdwar", state_id: 36 },
  { name: "Srinagar", state_id: 36 },
  { name: "Uttarkashi", state_id: 36 },
  { name: "Joshimath", state_id: 36 },
  { name: "Gangotri", state_id: 36 },
  { name: "Yamunotri", state_id: 36 },
  { name: "Badrinath", state_id: 36 },
  { name: "Kedarnath", state_id: 36 },
  { name: "Bhimtal", state_id: 36 },
  { name: "Pauri", state_id: 36 },
  // #West Bengal
  { name: "Kolkata", state_id: 37 },
  { name: "Howrah", state_id: 37 },
  { name: "Durgapur", state_id: 37 },
  { name: "Asansol", state_id: 37 },
  { name: "Siliguri", state_id: 37 },
  { name: "Bardhaman", state_id: 37 },
  { name: "Malda", state_id: 37 },
  { name: "Bardhaman", state_id: 37 },
  { name: "Kharagpur", state_id: 37 },
  { name: "Krishnanagar", state_id: 37 },
  { name: "Haldia", state_id: 37 },
  { name: "Raiganj", state_id: 37 },
  { name: "Bankura", state_id: 37 },
  { name: "Jalpaiguri", state_id: 37 },
  { name: "Cooch Behar", state_id: 37 },
  { name: "Alipurduar", state_id: 37 },
  { name: "Purulia", state_id: 37 },
  { name: "Darjeeling", state_id: 37 },
  { name: "Balurghat", state_id: 37 },
  { name: "Kalimpong", state_id: 37 },
  { name: "Ranaghat", state_id: 37 },
  { name: "Rampurhat", state_id: 37 },
  { name: "Murshidabad", state_id: 37 },
  { name: "Berhampore", state_id: 37 },
  { name: "Suri", state_id: 37 },
  { name: "Arambagh", state_id: 37 },
  { name: "Tamluk", state_id: 37 },
  { name: "Bakreswar", state_id: 37 },
  { name: "Bishnupur", state_id: 37 },
  { name: "Kalyani", state_id: 37 },
  { name: "Barasat", state_id: 37 },
  { name: "Bongaon", state_id: 37 },
  { name: "Baranagar", state_id: 37 },
  { name: "Chinsurah", state_id: 37 },
  { name: "Nabadwip", state_id: 37 },
];
export const up = async (queryInterface) => {
  const existingCity = await queryInterface.rawSelect(
    "cities",
    {
      where: {
        name: "Bambooflat",
      },
    },
    ["id"]
  );

  if (!existingCity) {
    // Add timestamps to each city record
    const dataWithTimestamps = cityData.map((city) => ({
      ...city,
      created_at: new Date(),
      updated_at: new Date(),
    }));

    await queryInterface.bulkInsert("cities", dataWithTimestamps);
  } else {
    console.log("Cities already exist!");
  }
};

export const down = async (queryInterface) => {
  await queryInterface.bulkDelete("cities", null, {});
};
