import "dotenv/config";
const appName = process.env.APP_NAME;
import authRoutes from "./authRoutes.js";
import streamRouter from "./streamRoutes.js";
import superAdminRoutes from "./superAdminRoutes.js";
import commonRouter from "./commonRoutes.js";
import teacherRouter from "./teacherRoutes.js";
import studentRouter from "./studentRoutes.js";
import classAndClassSectionRouter from "./classAndClassSectionRoutes.js";
import schoolSubjectRouter from "./schoolSubjectRoutes.js";
import syllabusRouter from "./syllabusRoutes.js";
import assessmentRouter from "./assessmentRoutes.js";
import chaptersRouter from "./chapterRoutes.js";
import reportRoutes from "./reportRoutes.js";
import notificationsRouter from "./notificationRoute.js";
import skillRoutes from "./skillsRoutes.js";
import courseRouter from "./courseRoutes.js";
import dashboardRouter from "./dashboardRoutes.js";
import chatRouter from "./chatRoutes.js";
import profileRouter from "./profileRoutes.js";
import contactUsRouter from "./contactUsRoutes.js";

export default (app) => {
    app.use(`/api/auth`, authRoutes);
    app.use(`/api/superAdmin`, superAdminRoutes);
    app.use(`/api/common`, commonRouter);
    app.use(`/api/stream`, streamRouter);
    app.use(`/api/teacher`, teacherRouter);
    app.use(`/api/student`, studentRouter);
    app.use(`/api/class`, classAndClassSectionRouter);
    app.use(`/api/school-subject`, schoolSubjectRouter);
    app.use(`/api/syllabus`, syllabusRouter);
    app.use(`/api/assessment`, assessmentRouter);
    app.use(`/api/chapters`, chaptersRouter);
    app.use(`/api/reports`, reportRoutes);
    app.use(`/api/notifications`, notificationsRouter);
    app.use(`/api/skills`, skillRoutes);
    app.use(`/api/course`, courseRouter);
    app.use(`/api/dashboard`, dashboardRouter);
    app.use(`/api/chat`, chatRouter);
    app.use(`/api/profile`, profileRouter);
    app.use(`/api/contact-us`, contactUsRouter);
};
