server {
    listen 80;
    server_name lms-frontend.local;

    root /usr/share/nginx/html;

    index index.html;

    # Frontend SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}

